### ISSUE TITLE
Add assert variant

### ISSUE THREAD

**Issue by sanex3339** [mesaugat/chai-exclude#10]
It is possible to add `assert` variant of this plugin?

**Comment by mesaugat** [comment]
Assert is not chainable. We will need to override the `assert.deepEqual` operation or create our own method itself.

How are you thinking of going about this? Any ideas or examples?

**Comment by sanex3339** [comment]
Just new method like:
`assert.deepEqualExcluding(foo, bar, 'baz');`

**Comment by mesaugat** [comment]
Makes sense. I'll look into it.

**Comment by mesaugat** [comment]
@sanex3339 I've just released a new version [1.0.6](https://github.com/mesaugat/chai-exclude/releases/tag/v1.0.6) with the assert variants.

* `assert.deepEqualExcluding`
* `assert.deepEqualExcludingEvery`

**Comment by sanex3339** [comment]
Thank you!
