### ISSUE TITLE
Issue with eql

### ISSUE THREAD

**Issue by luigidt** [mesaugat/chai-exclude#30]
Hello,

If you could check this repo: https://github.com/luigidt/exclude-issue

It gives me:

```
mocha --recursive

  1) compare dates with exclude
  √ compare dates without exclude

  1 passing (11ms)
  1 failing

  1) compare dates with exclude:

      AssertionError: expected { a: {} } to deeply equal { a: Thu, 01 Jan 1970 00:00:00 GMT }
      + expected - actual

       {
      -  "a": {}
      +  "a": [Date: 1970-01-01T00:00:00.000Z]
       }

      at Context.<anonymous> (test\index.js:10:16)
      at processImmediate (internal/timers.js:456:21)
```

Node version: v12.18.4

Is this behaviour expected?

Thank you

**Comment by mesaugat** [comment]
Hello @luigidt, thank you for reporting the issue. I have published a new version `2.0.3` with the fix. 

https://github.com/mesaugat/chai-exclude/commit/9243498f3f6e299c94943b5a55954b46a24eb30c
