### ISSUE TITLE
Support for excluding property in nested Array

### ISSUE THREAD

**Issue by gertwillems** [mesaugat/chai-exclude#38]
`                        expect(interception.request.body).excludingEvery('streetnumber').deep.equal({
                            kenmerk: KENMERK,
                            aangevraagdePercelen: [
                                {
                                    type: 'PERCEEL',
                                    adres: {
                                        straatnaam: 'street',
                                        streetnumber: 'randomSomething'
                                    }
                                }
                            ]
                        });
`

we would expect streetnumber to be excluded in all aangevraagdePercelen

**Comment by mesaugat** [comment]
@gertwillems It should work as expected. Can you give me a working example? What does `interception.request.body` look like?

Check below `streetnumber` is different in both objects but the test does pass as it excludes `streetnumber` from assertion.

```js
expect({
        kenmerk: 'KENMERK',
        aangevraagdePercelen: [{ type: 'PERCEEL', address: { streetname: 'street', streetnumber: 'randomSomething' } }]
      })
        .excludingEvery('streetnumber')
        .deep.equal({
          kenmerk: 'KENMERK',
          aangevraagdePercelen: [{ type: 'PERCEEL', address: { streetname: 'street', streetnumber: 'yolo' } }]
        });
```
