### ISSUE TITLE
Can you please help me with how can i ignore the order of arrays when comparing?

### ISSUE THREAD

**Issue by rahulworks-git** [mesaugat/chai-exclude#45]
I am using deepExcludingEvery and works perfect in my use case. But i also have another use case where i have to assert ignoring the order of elements present in JSON array.

**Comment by mesaugat** [comment]
@rahulworks-git Hello, can you provide an example? Do you mean you also want to assert the order of the array? If yes, this package doesn't do it.

**Comment by rahulworks-git** [comment]
@mesaugat Sure.


json_1 = {
    "data":
    [
        {
            "_id": "181",
            "date_time": "2008-03-11T22:24:00.000Z",
            "document_id": "111",
            "exp_id": "f7w7d6hs",
            "note_length": "5027"
        },
        {
            "_id": "182",
            "date_time": "2001-12-18T15:53:00.000Z",
            "document_id": "123",
            "encounter_id": "ha7sd7hahsd6",
            "note_length": "10400"
        },
        {
            "_id": "183",
            "date_time": "2001-11-20T01:43:00.000Z",
            "document_id": "134",
            "exp_id": "jjasd8721",
            "note_length": "6281"
        },
        {
            "note_id": "184",
            "date_time": "2009-10-03T21:46:00.000Z",
            "document_id": "167",
            "exp_id": "sadasd871hj2",
            "note_length": "5792"
        }
    ]
}

json_2 = {
    "data":
    [
        {
            "_id": "183",
            "date_time": "2001-11-20T01:43:00.000Z",
            "document_id": "134",
            "exp_id": "jjasd8721",
            "note_length": "6281"
        },
        {
            "_id": "181",
            "date_time": "2008-03-11T22:24:00.000Z",
            "document_id": "111",
            "exp_id": "f7w7d6hs",
            "note_length": "5027"
        }
        ,
        {
            "note_id": "184",
            "date_time": "2009-10-03T21:46:00.000Z",
            "document_id": "167",
            "exp_id": "sadasd871hj2",
            "note_length": "5792"
        },
        {
            "_id": "182",
            "date_time": "2001-12-18T15:53:00.000Z",
            "document_id": "123",
            "encounter_id": "ha7sd7hahsd6",
            "note_length": "10400"
        }
    ]
}

When i am using deepEqualExcludingEvery, then i get the response that the above 2 json are not the same whereas i am expecting them be the same. For my use case, the order of the records in an array does not matter, only the elements inside the array should not be different.

**Comment by mesaugat** [comment]
@rahulworks-git Got it. Deep equality in chai by default seems to also care about the order of the objects. (Didn't know about this 😅)

Maybe you can use this plugin: https://github.com/oprogramador/deep-equal-in-any-order

```js
expect(json_1).excludingEvery('a').to.deep.equalInAnyOrder(json_2)
```

**Comment by rahulworks-git** [comment]
@mesaugat This seemed to have worked partially. I need some help from you. Is it possible to connect over any meeting platform? Maybe i can share screen for a while and discuss the use case.

**Comment by mesaugat** [comment]
@rahulworks-git Hey sorry Rahul, I'm generally busy with my work. You can create an issue in the repository and I can take a look at it when I find the time.

Closing this issue for now.
