### ISSUE TITLE
Chai v5 support

### ISSUE THREAD

**Issue by Chebsi** [mesaugat/chai-exclude#48]
Hello there, I'm wondering if Chai v5 support is going to be added?

https://github.com/chaijs/chai/releases/tag/v5.0.0

**Comment by mesaugat** [comment]
@Chebsi Can't promise it right away. Will take a look when I find the time.

If you are able to send a pull request with the changes I can review.

**Comment by ThomasDenoncin** [comment]
Hello !
Could you please review those changes ?
https://github.com/mesaugat/chai-exclude/pull/51

**Comment by mesaugat** [comment]
`v3.0.0` is out. Thanks to @ThomasDenoncin
