### ISSUE TITLE
Deep equal comparison of MongoDB Object Ids always passes when using .excluding

### ISSUE THREAD

**Issue by cjsedwards** [mesaugat/chai-exclude#49]
The test below always passes. If you remove the .excluding, it always fails.
mongodb - 4.17.1
mongoose - 6.12.3
chai - 4.3.10
chai-exclude - 2.1.0

```
describe('ObjectId comparison', () => {
  it('Compare ObjectIds with .excluding', () => {
    expect(new ObjectId()).excluding('anything').to.deep.equal(new ObjectId())
  })
})
```

I believe the culprit is fclone, which appears to strip out the internals of ObjectIds

**Comment by cjsedwards** [comment]
Hi there, I see someone put eyeballs on this.  Has anyone had a chance to look at this?

**Comment by mesaugat** [comment]
@cjsedwards Hey sorry, the test that you've provided doesn't pass. It is working as intended. Can you please check again? I am also using version `2.1.0`.

If you remove `excluding` it will always fail which is correct because you are initializing two different `ObjectId()`s.

**Comment by cjsedwards** [comment]
Hi @mesaugat , I just confirmed again then we I run the above code, the test passes, when it should be failing.

The version of mongodb you have is important, as we noticed this behaviour change when upgrading.  Something about the internals of ObjectId now look different and are being stripped out by fclone.

I I do a deep equals (when using chai-exclude), the internals of ObjectId show up as completely empty.

**Comment by mesaugat** [comment]
@cjsedwards If the newer version of mongodb doesn't have this issue, I hope you can upgrade to a newer version of mongodb to avoid this issue.

Replacing fclone is out of question right now. fclone is a pretty old package as well which I can look to replace later.

**Comment by cjsedwards** [comment]
The newer version is the one with the issue.

**Comment by cjsedwards** [comment]
I did check, and using cloneDeep in lodash appears to preserve the internals of ObjectId, so if you're looking at a replacement that might be an option.

**Comment by mesaugat** [comment]
@cjsedwards I checked with the latest version of mongodb. It doesn't seem to have the issue.

I ran the same test as you did.

**Comment by cjsedwards** [comment]
Interesting... When I have some more time I'll put together a repo to demonstrate the problem.

**Comment by mesaugat** [comment]
Closing because the issue is stale. @cjsedwards Please reopen if this is a recurring problem.
