### ISSUE TITLE
Error: Invalid Chai property: excludingEvery

### ISSUE THREAD

**Issue by brettz9** [mesaugat/chai-exclude#52]
Hi,

For some reason, despite upgrading to chai 5.1.1, and chai-exclude 3.0.0, I'm getting the error:

> Error: Invalid Chai property: excludingEvery

I am performing the set-up as well:

```js
import * as chai from 'chai';
import chaiExclude from 'chai-exclude';
chai.use(chaiExclude);
```

Any idea what could be happening? Was this property overlooked or something?

Thanks!

**Comment by mesaugat** [comment]
@brettz9 Is this still a problem?

**Comment by brettz9** [comment]
Can't remember the environment I was using for this atm, but it works fine on a fresh install, thanks!
