### ISSUE TITLE
exclude property path

### ISSUE THREAD

**Issue by mathroc** [mesaugat/chai-exclude#9]
sometime I might want to ignore properties only at certain level, eg:

```js
expect({
  id: 123,
  a: {
    id: 345,
    b: "c",
  }
}).excludingPath(["a", "id"]).to.deep.equals({
  id: 123,
  a: {
    b: "c",
  }
})
```

do you think `excludingPath` would be useful ? I’ve worked around it for now by not testing some properties but I’d like to make a PR sometime if you think that would be useful

**Comment by mesaugat** [comment]
Not really sure how helpful this is going to be. Also, `excludingPath['a', 'id']` is hard to understand. Also, how deep should we go?

**Comment by mathroc** [comment]
I’m not sure I understand so here are a few other examples of what I have in mind :

```js
expect({
  id: 123,
  a: {
    id: 345,
    b: "c",
  }
}).excludingPath(["a"]).to.deep.equals({
  id: 123,
})
```

```js
expect({
  id: 123,
  a: {
    id: 345,
    b: "c",
    a: {
      id: 678
    }
  }
}).excludingPath(["a", "id"]).to.deep.equals({
  id: 123,
  a: {
    b: "c",
    a: {
      id: 678
    }
  }
})
```

```js
expect({
  id: 123,
  a: {
    id: 345,
    b: "c",
    a: {
      id: 678
    }
  }
}).excludingPath(["a", "a", "id"]).to.deep.equals({
  id: 123,
  a: {
    id: 456,
    b: "c",
    a: {}
  }
})
```

just realized that the arguments don’t need to be in an array, a variadic function works well here: 

```js
expect({
  id: 123,
  a: {
    id: 345,
    b: "c",
    a: {
      id: 678
    }
  }
}).excludingPath("a", "id").to.deep.equals({
  id: 123,
  a: {
    b: "c",
    a: {
      id: 678
    }
  }
})
```

does that answer your question ? this is mainly to avoid removing all properties having the same name from the object

**Comment by mesaugat** [comment]
And how do you go about excluding various paths and not one? Maybe an array of strings?

`excludingPath(['a', 'b'], ['d', 'e'])`

```js
{
  a: {
    b: 'c',
    z: 'y'
  },
  d: {
    e: 'd',
    f: 'g'
  }
}
```

I feel we are trying to do too much here?

**Comment by mathroc** [comment]
@mesaugat you can always call `excludingPath` multiple times to exclude multiple paths, or for the sake of consistency, there could be a `excludingPaths`

imho, excluding path one at a time is enough so I don’t mind having `excludingPaths` or not and handling multiple paths in `excludingPath` or not

> I feel we are trying to do too much here?

I don’t want to force anything, if you think this outside the scope of chai-exclude, I’ll just add this into my project until I have time to make another plugin

**Comment by mesaugat** [comment]
My only requirement is that the API should be simple to understand. Feel free to send a pull request and then we can discuss about the code itself.

**Comment by mesaugat** [comment]
@mathroc I am closing this issue. Hope you have figured out the solution. If you want to reopen this issue feel free to do so. We can discuss further.
